export enum AppRoute {
  Root = '/',
  Unlock = '/unlock',
  RetrieveNodeAccess = '/retrieve-node-access',
  AppInit = '/app-init',
  MyNode = '/my-node',
  Rewards = '/rewards',

  AddTask = '/add-tasks',
  MyTokens = '/my-tokens',
  Notifications = '/notifications',
  Referral = '/referrals',
  Settings = '/settings',
  SettingsGeneral = '/settings/general',
  SettingsSecurity = '/settings/security',
  SettingsExtensions = '/settings/extensions',
  SettingsAutomateNode = '/settings/automate-node',
  SettingsNotifications = '/settings/notifications',
  SettingsNetworkAndUPNP = '/settings/network',
  SettingsWallet = '/settings/wallet',
  SettingsHelp = '/settings/help',
  SettingsPrivacy = '/settings/privacy',
  History = '/history',
  Onboarding = '/onboarding',
  // onboarding routes
  OnboardingInitialScreen = '/onboarding/initial-screen',
  OnboardingCreatePin = '/onboarding/create-pin',
  OnboardingCreateOrImportKey = '/onboarding/create-or-import-key',
  OnboardingCreateNewKey = '/onboarding/create-or-import-key/create-new-key',
  OnboardingPickKeyCreationMethod = '/onboarding/create-or-import-key/pick-key-creation-method',
  OnboardingImportKey = '/onboarding/create-or-import-key/import-key',
  OnboardingBackupKeyNow = '/onboarding/create-or-import-key/backup-key-now',
  OnboardingConfirmSecretPhrase = '/onboarding/create-or-import-key/confirm-backup-secret-phrase',
  OnboardingPhraseImportSuccess = '/onboarding/create-or-import-key/import-key/phrase-import-success',
  OnboardingPhraseSaveSuccess = '/onboarding/create-or-import-key/import-key/phrase-save-success',
  OnboardingGetFreeTokens = '/onboarding/create-or-import-key/get-free-tokens',
  OnboardingFundNewKey = '/onboarding/create-or-import-key/fund-new-key',
  OnboardingSeeBalance = '/onboarding/create-or-import-key/see-balance',
  OnboardingCreateFirstTask = '/onboarding/create-first-task',
  OnboardingConfirmStake = '/onboarding/confirm-stake',
}

export enum DeepLinkRoute {
  MyNode = '/my-node',
  AddTask = '/add-tasks',
  Notifications = '/notifications',
  Referral = '/referrals',
  SettingsGeneral = '/settings/general',
  SettingsNetworkAndUPNP = '/settings/network',
  SettingsWallet = '/settings/wallet',
  SettingsHelp = '/settings/help',
  SettingsExtensions = '/settings/extensions',
}
