export interface DetailedError {
  detailed: string;
  type: ErrorType;
}

export enum ErrorType {
  CONTRACT_ID_NOT_FOUND = 'CONTRACT_ID_NOT_FOUND',
  NO_ACTIVE_ACCOUNT = 'NO_ACTIVE_ACCOUNT',
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  NO_TASK_SOURCECODE = 'NO_TASK_SOURCECODE',
  NO_TASK_METADATA = 'NO_TASK_METADATA',
  NO_RUNNING_TASK = 'NO_RUNNING_TASK',
  NO_ACCOUNT_KEY = 'NO_ACCOUNT_KEY',
  TRANSACTION_TIMEOUT = 'TRANSACTION_TIMEOUT',
  NO_MNEMONIC = 'NO_MNEMONIC',
  NO_VALID_MNEMONIC = 'NO_VALID_MNEMONIC',
  NO_VALID_ACCOUNT_NAME = 'NO_VALID_ACCOUNT_NAME',
  GENERIC = 'GENERIC',
  DUPLICATE_ACCOUNT = 'DUPLICATE_ACCOUNT',
  NODE_INITIALIZATION_FAILED = 'INITIALIZATION_FAILED',
  TASK_START = 'TASK_START',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  NO_JSON_KEY = 'NO_JSON_KEY',
  ACCOUNT_NAME_EXISTS = 'ACCOUNT_NAME_EXISTS',
  JSON_KEY_EXISTS = 'JSON_KEY_EXISTS',
  PARTIAL_CLAIM_FAILURE = 'PARTIAL_CLAIM_FAILURE',
  FETCHING_NEXT_REWARD_FAILED = 'FETCHING_NEXT_REWARD_FAILED',
  INVALID_SCHEDULE_SESSION_TIME_RANGE = 'INVALID_SCHEDULE_SESSION_TIME_RANGE',
  SCHEDULE_SAME_START_STOP_TIMES = 'SCHEDULE_SAME_START_STOP_TIMES',
  SCHEDULE_NO_SELECTED_DAYS = 'SCHEDULE_NO_SELECTED_DAYS',
  SCHEDULE_OVERLAP = 'SCHEDULE_OVERLAP',
  INVALID_WALLET_ADDRESS = 'INVALID_WALLET_ADDRESS',
  INSUFFICIENT_FUNDS_FOR_FEES = 'INSUFFICIENT_FUNDS_FOR_FEES',
  FETCH_ACCOUNT_BALANCE = 'FETCH_ACCOUNT_BALANCE',
  RPC_STATUS_FETCH_FAILED = 'RPC_STATUS_FETCH_FAILED',
  UNSTAKE_UNAVAILABLE = 'UNSTAKE_UNAVAILABLE',
  TOKEN_TRANSFER_FAILED = 'TOKEN_TRANSFER_FAILED',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  KPL_TOKEN_TRANSFER_FAILED = 'TPL_TOKEN_TRANSFER_FAILED',
}

export enum NetworkErrors {
  TRANSACTION_TIMEOUT = 'transaction was not confirmed',
  NO_REWARD_PENDING_ON_TASK = "The provided claimer account doesn't have any balance on task state",
  INSUFFICIENT_FUNDS_FOR_FEES = 'Attempt to debit an account but found no record of a prior credit',
}
